# uma lista de palavras para testar o jogo
game_words = {
    "Animal": [
        {"word": 'Leão', "desc": "Grande felino carnívoro, conhecido como o 'rei da selva'.",},
        {"word": 'Pato', "desc": "Ave aquática com bico achatado, comum em lagos e rios.",},
        {"word": 'Papagaio', "desc": "Ave colorida e inteligente, famosa por imitar sons e vozes humanas.",},
        {"word": 'Flamingo', "desc": "Ave alta e rosa, com pernas longas e hábito de se alimentar em águas rasas.",},
        {"word": 'Ornitorrinco', "desc": "Mamífero australiano que bota ovos, tem bico de pato e cauda de castor.",},
        {"word": 'Tamanduá', "desc": "Mamífero de focinho comprido, especializado em comer formigas e cupins.",},
        {"word": 'Golfinho', "desc": "Mamífero marinho inteligente, conhecido por sua sociabilidade e saltos acrobáticos.",},
        {"word": 'Libélula', "desc": "Inseto com asas transparentes, excelente voo e comum perto de água doce.",},
        {"word": 'Jacaré', "desc": "Répil com corpo alongado e dentes afiados, vive em áreas alagadas e rios.",},
        {"word": 'Tatu', "desc": "Mamífero com carapaça rígida, escava tocas e se enrola para se proteger.",},
        {"word": 'Anta', "desc": "Grande mamífero herbívoro da América do Sul, com corpo robusto e focinho flexível.",},
        {"word": 'Escaravelho', "desc": "Inseto com carapaça dura, famoso por rolar bolas de esterco.",},
        {"word": 'Coruja', "desc": "Ave noturna com excelente visão, conhecida por seu voo silencioso.",},
        {"word": 'Camaleão', "desc": "Réptil que muda de cor, tem olhos independentes e língua pegajosa.",},
        {"word": 'Cavalo-marinho', "desc": "Pequeno peixe com corpo alongado e cabeça em forma de cavalo.",},
        {"word": 'Preguiça', "desc": "Mamífero de movimentos lentos que passa a maior parte do tempo pendurado em árvores.",},
        {"word": 'Canguru', "desc": "Marsupial australiano que salta longas distâncias e carrega filhotes na bolsa.",},
        {"word": 'Avestruz', "desc": "A maior ave do mundo, incapaz de voar, mas corre em alta velocidade.",},
        {"word": 'Enguia-elétrica', "desc": "Peixe capaz de gerar descargas elétricas para se defender e caçar.",},
        {"word": 'Urso-pardo', "desc": "Grande mamífero onívoro, forte e adaptável a diversos habitats.",},
        {"word": 'Estrela-do-mar', "desc": "Animal marinho de corpo estrelado, capaz de regenerar braços.",},
        {"word": 'Serpente', "desc": "Réptil alongado, sem pernas, que se move rastejando.",},
        {"word": 'Pelicano', "desc": "Ave com grande bolsa no bico usada para pescar peixes.",},
        {"word": 'Lêmure', "desc": "Primata de olhos grandes, ativo ao amanhecer e anoitecer, típico de Madagascar.",},
        {"word": 'Morcego', "desc": "Único mamífero capaz de voar, ativo principalmente à noite.",},
        {"word": 'Caranguejo', "desc": "Crustáceo de pinças fortes que anda de lado e vive próximo à água.",},
        {"word": 'Foca', "desc": "Mamífero marinho de corpo roliço e nadadeiras curtas, ágil na água.",},
        {"word": 'Guaxinim', "desc": "Mamífero noturno com máscara facial e hábitos oportunistas.",},
        {"word": 'Galo', "desc": "Ave doméstica conhecida por cantar ao amanhecer.",},
        {"word": 'Escorpião', "desc": "Aracnídeo com cauda curva e ferrão venenoso na ponta.",},
        {"word": 'Lula-gigante', "desc": "Molusco colossal dos mares profundos, com tentáculos enormes.",},
        {"word": 'Sapo', "desc": "Anfíbio robusto e de canto grave, comum em áreas úmidas.",},
        {"word": 'Tigre', "desc": "Grande felino listrado, ágil e poderoso caçador.",},
        {"word": 'Mariposa', "desc": "Inseto noturno, com asas com cores mais discretas.",},
        {"word": 'Caracol', "desc": "Molusco com concha em espiral que se move lentamente.",},
        {"word": 'Polvo', "desc": "Molusco marinho inteligente, mestre em camuflagem.",},
        {"word": 'Centopéia', "desc": "Artrópode alongado com muitas pernas e movimentos rápidos.",},
        {"word": 'Piranha', "desc": "Peixe carnívoro de dentes afiados, encontrado em rios da América do Sul.",},
        {"word": 'Cavalo', "desc": "Mamífero herbívoro veloz, usado pelo homem para transporte e esporte.",},
        {"word": 'Tarântula', "desc": "Grande aranha peluda, geralmente inofensiva para humanos.",},
        {"word": 'Mosquito', "desc": "Inseto voador pequeno, suas picadas que podem transmitir doenças.",},

    ],
    
    "Comida": [
        {"word": 'Arroz Carreteiro', "desc": "Prato típico do sul do Brasil feito com arroz, carne e temperos.",},
        {"word": 'Estrogonofe de Frango', "desc": "Frango cremoso com molho de creme de leite e ketchup, geralmente servido com arroz e batata palha.",},
        {"word": 'Macarrão', "desc": "Massa versátil, geralmente servida com molhos como bolonhesa, branco ou alho e óleo.",},
        {"word": 'Panqueca', "desc": "Massa fina e recheada, que pode ser doce ou salgada.",},
        {"word": 'Almondegas', "desc": "Bolinhas de carne moída temperadas, muitas vezes servidas com molho de tomate.",},
        {"word": 'Bolo de Cenoura com Cobertura de Chocolate', "desc": "Clássico bolo fofo de cenoura com uma generosa camada de calda de chocolate por cima.",},
        {"word": 'Figado', "desc": "Carne de sabor forte, rica em ferro, que divide opiniões.",},
        {"word": 'MilkShake de Morango', "desc": "Bebida gelada, doce e cremosa feita com sorvete de morango.",},
        {"word": 'Coxinha', "desc": "Salgadinho brasileiro em forma de gota, recheado com frango e empanado.",},
        {"word": 'Pé de Galinha', "desc": "Prato polêmico feito com os pés da galinha, muito consumido em caldos ou cozidos.",},
        {"word": 'Sardinha', "desc": "Peixe pequeno e saboroso, pode ser servido grelhado, em lata ou em preparos caseiros.",},
        {"word": 'Quiabo', "desc": "Vegetal verde, polêmico por sua textura viscosa, comum em pratos como frango com quiabo.",},
        {"word": 'Pamonha Doce', "desc": "Quitute típico de milho cozido, envolto em palha, com sabor adocicado.",},
        {"word": 'Brocolis', "desc": "Vegetal verde rico em fibras e nutrientes, geralmente cozido ou refogado.",},
        {"word": 'Água', "desc": "Líquido comum para hidratação.",},
        {"word": 'Feijoada', "desc": "Prato típico brasileiro feito com feijão-preto e carnes variadas.",},
        {"word": 'Moqueca de Peixe', "desc": "Ensopado de peixe com leite de coco, azeite de dendê e temperos, típico da Bahia e do Espírito Santo.",},
        {"word": 'Tapioca', "desc": "Massa de goma de mandioca hidratada, que pode ser recheada com opções doces ou salgadas.",},
        {"word": 'Esfiha', "desc": "Massa assada ou frita recheada com carne, queijo ou verduras, típica da culinária árabe.",},
        {"word": 'Pastel', "desc": "Massa fina e crocante frita, recheada com carne, queijo, frango ou outros sabores.",},
        {"word": 'Brigadeiro', "desc": "Doce brasileiro feito com leite condensado, chocolate e manteiga, enrolado e coberto com granulado.",},
        {"word": 'Empadão de Frango', "desc": "Torta salgada recheada com frango, milho e azeitonas.",},
        {"word": 'Pão de Queijo', "desc": "Bolinhas macias e elásticas feitas com polvilho e queijo, típicas de Minas Gerais.",},
        {"word": 'Sorvete', "desc": "Sobremesa gelada e cremosa de sabores variados.",},
        {"word": 'Yakissoba', "desc": "Macarrão oriental salteado com legumes, carne e molho à base de shoyu.",},
        {"word": 'Lasanha', "desc": "Camadas de massa intercaladas com molho, carne e queijo.",},
        {"word": 'Bolinho de Chuva', "desc": "Pequenos bolinhos fritos, polvilhados com açúcar e canela, típicos de lanche da tarde.",},
        {"word": 'Canjica', "desc": "Sobremesa de milho branco cozido com leite, açúcar e canela, típica das festas juninas.",},
        {"word": 'Cuscuz', "desc": "Prato de milho floculado cozido no vapor, servido com manteiga ou acompanhamentos variados.",},
        {"word": 'Omelete', "desc": "Ovos batidos e cozidos em frigideira, podendo levar recheios variados.",},

    ],
    
    "Objeto": [
        {"word": 'Grampeador', "desc": "Objeto de escritório usado para prender folhas de papel com grampos de metal.",},
        {"word": 'Relogio de pendulo', "desc": "Relógio antigo que funciona com um pêndulo oscilante, geralmente decorativo.",},
        {"word": 'Canivete', "desc": "Ferramenta dobrável com lâminas e acessórios, útil em situações práticas e de sobrevivência.",},
        {"word": 'Lanterna', "desc": "Dispositivo portátil usado para iluminar ambientes escuros com luz artificial.",},
        {"word": 'Garrafa térmica', "desc": "Recipiente que conserva líquidos quentes ou frios por mais tempo.",},
        {"word": 'Lampião', "desc": "Fonte de luz antiga alimentada por querosene, comum antes da eletricidade.",},
        {"word": 'Maçaneta', "desc": "Peça usada para abrir ou fechar portas, geralmente giratória.",},
        {"word": 'Travesseiro', "desc": "Almofada macia usada para apoiar a cabeça durante o sono.",},
        {"word": 'Cutelo', "desc": "Faca grande e pesada usada principalmente para cortar carne com osso.",},
        {"word": 'Tapete', "desc": "Peça de tecido ou material sintético colocada no chão para conforto ou decoração.",},
        {"word": 'Cortador de Grama', "desc": "Equipamento usado para aparar a grama em jardins e quintais.",},
        {"word": 'Abridor de Coco', "desc": "Ferramenta projetada para perfurar ou abrir cocos com segurança.",},
        {"word": 'Chaleira Elétrica', "desc": "Aparelho que aquece água rapidamente por meio de resistência elétrica.",},
        {"word": 'Memory Card de PS2', "desc": "Cartão de memória usado para salvar o progresso dos jogos no PlayStation 2.",},
        {"word": 'Alicate', "desc": "Ferramenta usada para apertar, cortar ou dobrar fios e metais.",},
        {"word": 'Ventilador', "desc": "Aparelho que movimenta o ar para refrescar o ambiente.",},
        {"word": 'Capacete', "desc": "Equipamento de proteção para a cabeça, usado em construções ou para andar de moto.",},
        {"word": 'Cofre', "desc": "Caixa segura para guardar dinheiro e objetos de valor, geralmente com fechadura ou senha.",},
        {"word": 'Binóculo', "desc": "Dispositivo óptico usado para observar objetos distantes com ampliação.",},
        {"word": 'Teclado Mecânico', "desc": "Teclado com switches individuais, popular entre gamers e digitadores.",},
        {"word": 'Furadeira', "desc": "Ferramenta elétrica usada para fazer furos em diferentes materiais.",},
        {"word": 'Chave Inglesa', "desc": "Ferramenta ajustável usada para apertar ou soltar porcas e parafusos.",},
        {"word": 'Mochila', "desc": "Bolsa com alças usada nas costas para carregar objetos.",},
        {"word": 'Micro-ondas', "desc": "Eletrodoméstico que aquece e cozinha alimentos rapidamente usando ondas eletromagnéticas.",},
        {"word": 'Trena', "desc": "Fita de medição usada para medir distâncias e tamanhos.",},
        {"word": 'Aspirador de Pó', "desc": "Aparelho que suga poeira e sujeira de pisos e superfícies.",},
        {"word": 'Bússola', "desc": "Instrumento de navegação que indica a direção norte magnético.",},
        {"word": 'Caixa de Som', "desc": "Dispositivo que reproduz som a partir de sinais de áudio.",},
        {"word": 'Câmera Polaroid', "desc": "Câmera que revela fotos instantaneamente após tirá-las.",},
        {"word": 'Castiçal', "desc": "Suporte fixo para velas, geralmente encontrado em casas antigas ou castelos.",},
        {"word": 'Caixa Registradora', "desc": "Máquina mecânica usada para registrar vendas e guardar dinheiro.",},
        {"word": 'Máquina de Escrever', "desc": "Maquina antida usada para escreve textos, utiliza de tinta para escrever.",},
        {"word": 'Afiador de Facas', "desc": "Objeto utilizado para afiar/amolar facas.",},
    ],
    
    "Monstro":[
        {"word": 'Minotauro', "desc": "Criatura da mitologia grega com corpo de homem e cabeça de touro.",},
        {"word": 'Bicho-Papão', "desc": "Monstro folclórico usado para assustar crianças desobedientes, vive debaixo da cama ou no armário.",},
        {"word": 'Chupa-Cabra', "desc": "Criatura lendária que ataca animais e suga seu sangue.",},
        {"word": 'Zumbi', "desc": "Cadáver reanimado, geralmente lento e faminto por cérebros ou carne humana.",},
        {"word": 'Medusa', "desc": "Monstro da mitologia grega com cobras no lugar dos cabelos; quem a encara vira pedra.",},
        {"word": 'Vampiro', "desc": "Ser noturno que se alimenta de sangue humano, teme o sol, estacas e alho.",},
        {"word": 'Dragão', "desc": "Criatura mitológica gigante, geralmente com asas e que cospe fogo.",},
        {"word": 'Lobisomen', "desc": "Humano que se transforma em lobo nas noites de lua cheia, presente em várias culturas.",},
        {"word": 'Freddie Krugger', "desc": "Vilão dos sonhos que usa uma luva com lâminas para atacar suas vítimas enquanto dormem.",},
        {"word": 'Godzilla', "desc": "Monstro gigante japonês, surgido por radiação, famoso por destruir cidades.",},
        {"word": 'Curupira', "desc": "Ser do folclore brasileiro com cabelos vermelhos e pés virados para trás, protetor das florestas.",},
        {"word": 'Saci', "desc": "Personagem travesso do folclore brasileiro, de uma perna só, gorro vermelho e sempre em redemoinhos.",},
        {"word": 'Homem do Saco', "desc": "Figura folclórica usada para amedrontar crianças; diz-se que carrega os desobedientes num saco.",},
        {"word": 'Múmia', "desc": "Cadáver embalsamado do Egito antigo, que ganha vida em histórias de terror.",},
        {"word": 'Quimera', "desc": "Criatura mitológica com cabeça de leão, corpo de cabra e cauda de serpente.",},
        {"word": 'Frankenstein', "desc": "Criatura feita a partir de partes de corpos humanos e trazida à vida por um cientista.",},
        {"word": 'Pennywise', "desc": "O palhaço demoníaco do livro e filme 'It', de Stephen King.",},
        {"word": 'Predador', "desc": "Caçador alienígena altamente tecnológico que busca presas perigosas.",},
        {"word": 'Slender Man', "desc": "Figura alta e sem rosto que persegue e sequestra pessoas.",},
        {"word": 'Bruxa', "desc": "Figura mágica associada a feitiçaria e maldições.",},


    ],
    
    "Profissão":[
        {"word": 'Médico', "desc": "Profissional da saúde que diagnostica e trata doenças.",},
        {"word": 'Professor', "desc": "Responsável por ensinar e educar em diversas áreas do conhecimento.",},
        {"word": 'Engenheiro', "desc": "Profissional que projeta e constrói soluções para problemas técnicos.",},
        {"word": 'Advogado', "desc": "Especialista em leis que defende e orienta juridicamente seus clientes.",},
        {"word": 'Policial', "desc": "Responsável por manter a ordem e proteger a população.",},
        {"word": 'Bombeiro', "desc": "Profissional que combate incêndios e realiza resgates.",},
        {"word": 'Piloto de avião', "desc": "Conduz aeronaves para transporte de pessoas ou cargas.",},
        {"word": 'Chef de cozinha', "desc": "Profissional especializado no preparo de pratos e cardápios.",},
        {"word": 'Ator', "desc": "Interpreta personagens em peças teatrais, filmes e séries.",},
        {"word": 'Cantor', "desc": "Profissional que se apresenta interpretando músicas.",},
        {"word": 'Programador', "desc": "Desenvolve sistemas, aplicativos e softwares.",},
        {"word": 'Astronauta', "desc": "Profissional treinado para realizar missões no espaço.",},
        {"word": 'Detetive particular', "desc": "Investiga casos de forma privada, buscando provas e informações.",},
        {"word": 'Barbeiro', "desc": "Corta e estiliza cabelos e barbas.",},
        {"word": 'Arqueólogo', "desc": "Estuda vestígios de culturas passadas e faz descobertas históricas.",},
        {"word": 'Agricultor', "desc": "Cultiva alimentos e cuida de plantações.",},
        {"word": 'Veterinário', "desc": "Cuida da saúde de animais domésticos e silvestres.",},
        {"word": 'Motorista de caminhão', "desc": "Transporta cargas em longas distâncias.",},
        {"word": 'Carpinteiro', "desc": "Constrói e repara estruturas e objetos de madeira.",},
        {"word": 'Pescador', "desc": "Profissional que captura peixes e frutos do mar para consumo ou venda.",},
        {"word": 'Exorcista', "desc": "Especialista em expulsar supostos espíritos malignos de pessoas ou lugares.",},
        {"word": 'Escravo', "desc": "Alguém submetido à vontade de um senhor, a quem pertence como propriedade.",},

    ],
    
    "Lugar":[
        {"word": 'Praia', "desc": "Área de areia ou pedras à beira-mar, popular para lazer e banho.",},
        {"word": 'Escola', "desc": "Instituição onde as pessoas vão para aprender.",},
        {"word": 'Supermercado', "desc": "Loja grande que vende alimentos e produtos variados.",},
        {"word": 'Parque', "desc": "Área verde pública para lazer e atividades ao ar livre.",},
        {"word": 'Aeroporto', "desc": "Local onde aviões pousam e decolam, para transporte de passageiros.",},
        {"word": 'Floresta de Aokigahara', "desc": "Também chamada de Floresta do Suicídio, no Japão, conhecida pela sua atmosfera sombria e história trágica.",},
        {"word": 'Portão do Inferno', "desc": "Cratera de gás natural em chamas no Turcomenistão, que queima constantemente desde 1971.",},
        {"word": 'Padaria', "desc": "Estabelecimento que vende pães, bolos e outros produtos de confeitaria.",},
        {"word": 'Loja de Animais', "desc": "Comércio especializado na venda de pets, rações e acessórios.",},
        {"word": 'Farmácia', "desc": "Lugar onde se vendem medicamentos e produtos de saúde.",},
        {"word": 'Restaurante', "desc": "Estabelecimento onde se servem refeições para consumo no local.",},
        {"word": 'Banco', "desc": "Local onde se realizam operações financeiras como depósitos e empréstimos.",},
        {"word": 'Posto de Gasolina', "desc": "Estação onde veículos abastecem combustível.",},
        {"word": 'Shopping', "desc": "Centro comercial com diversas lojas, cinemas e áreas de lazer.",},
        {"word": 'Biblioteca', "desc": "Espaço que disponibiliza livros e materiais para leitura e estudo.",},
        {"word": 'Cinema', "desc": "Local onde são exibidos filmes para o público.",},
        {"word": 'Hospital', "desc": "Instituição que presta atendimento médico e hospitalar.",},
        {"word": 'Monte Everest', "desc": "Montanha de maior altitude da Terra, localizada no Tibete.",},
        {"word": 'Cemitério', "desc": "Local onde se enterram os mortos.",},
        {"word": 'Banheiro', "desc": "Local onde as pessoas fazem suas necessidades.",},
        {"word": 'Elevador', "desc": "Local de transporte vertical, geralmente se encontra em construções altas.",},
    ],
    
    "Veículos":[
        {"word": 'Bicicleta', "desc": "Veículo de duas rodas movido pela força das pernas do ciclista.",},
        {"word": 'Carro', "desc": "Veículo motorizado comum para transporte individual ou em grupo.",},
        {"word": 'Metrô', "desc": "Sistema de transporte coletivo subterrâneo em grandes cidades.",},
        {"word": 'Avião', "desc": "Veículo aéreo que transporta pessoas e cargas por longas distâncias.",},
        {"word": 'Barco', "desc": "Meio de transporte usado em rios, lagos e no mar.",},
        {"word": 'Trem', "desc": "Veículo que circula sobre trilhos, usado para transporte de passageiros e cargas.",},
        {"word": 'Skate', "desc": "Prancha com rodas usada para deslocamento e manobras urbanas.",},
        {"word": 'Patinete elétrico', "desc": "Transporte individual elétrico, popular em cidades.",},
        {"word": 'Helicóptero', "desc": "Aeronave com hélices que permite pousos e decolagens verticais.",},
        {"word": 'Triciclo', "desc": "Veículo com três rodas, usado por crianças ou para transporte leve.",},
        {"word": 'Canoa', "desc": "Pequeno barco estreito, geralmente movido a remo.",},
        {"word": 'Caminhão', "desc": "Veículo grande usado para transportar cargas pesadas.",},
        {"word": 'Submarino', "desc": "Veículo aquatico que se locomove abaixo da água.",},
        {"word": 'Ônibus', "desc": "Veículo coletivo usado para transportar várias pessoas em trajetos urbanos ou rodoviários.",},
        {"word": 'Bondinho', "desc": "Veículo que circula sobre trilhos em declives, comum em áreas turísticas.",},
        {"word": 'Elevador', "desc": "Local de transporte vertical, geralmente se encontra em construções altas.",},

    ]
    }