# uma lista de palavras para testar o jogo
game_words = {
    "Animal": [
        {"word": 'Leão', "desc": "Grande felino carnívoro,\n conhecido como o 'rei da selva'.",},
        {"word": 'Pato', "desc": "Ave aquática com bico achatado,\n comum em lagos e rios.",},
        {"word": 'Papagaio', "desc": "Ave colorida e inteligente,\n famosa por imitar sons e vozes humanas.",},
        {"word": 'Flamingo', "desc": "Ave alta e rosa, com pernas longas e\n hábito de se alimentar em águas rasas.",},
        {"word": 'Ornitorrinco', "desc": "Mamífero australiano que bota ovos,\n tem bico de pato e cauda de castor.",},
        {"word": 'Tamanduá', "desc": "Mamífero de focinho comprido,\n especializado em comer formigas e cupins.",},
        {"word": 'Golfinho', "desc": "Mamífero marinho inteligente,\n conhecido por sua sociabilidade e saltos acrobáticos.",},
        {"word": 'Libélula', "desc": "Inseto com asas transparentes,\n excelente voo e comum perto de água doce.",},
        {"word": 'Jacaré', "desc": "Répil com corpo alongado e dentes afiados,\n vive em áreas alagadas e rios.",},
        {"word": 'Tatu', "desc": "Mamífero com carapaça rígida,\n escava tocas e se enrola para se proteger.",},
        {"word": 'Anta', "desc": "Grande mamífero herbívoro da América do Sul,\n com corpo robusto e focinho flexível.",},
        {"word": 'Escaravelho', "desc": "Inseto com carapaça dura,\n famoso por rolar bolas de esterco.",},
        {"word": 'Coruja', "desc": "Ave noturna com excelente visão,\n conhecida por seu voo silencioso.",},
        {"word": 'Camaleão', "desc": "Réptil que muda de cor,\n tem olhos independentes e língua pegajosa.",},
    ],
    
    "Comida": [
        {"word": 'Arroz Carreteiro', "desc": "Prato típico do sul do Brasil\n feito com arroz, carne e temperos.",},
        {"word": 'Estrogonofe de Frango', "desc": "Frango cremoso com molho de creme\n de leite e ketchup, geralmente servido com arroz e batata palha.",},
        {"word": 'Macarrão', "desc": "Massa versátil, geralmente servida com molhos\n como bolonhesa, branco ou alho e óleo.",},
        {"word": 'Panqueca', "desc": "Massa fina e recheada,\n que pode ser doce ou salgada.",},
        {"word": 'Almondegas', "desc": "Bolinhas de carne moída temperadas,\n muitas vezes servidas com molho de tomate.",},
        {"word": 'Bolo de Cenoura com Cobertura de Chocolate', "desc": "Clássico bolo fofo de cenoura\n com uma generosa camada de calda de chocolate por cima.",},
        {"word": 'Figado', "desc": "Carne de sabor forte,\n rica em ferro,\n que divide opiniões.",},
        {"word": 'MilkShake de Morango', "desc": "Bebida gelada, doce e cremosa\n feita com sorvete de morango.",},
        {"word": 'Coxinha', "desc": "Salgadinho brasileiro em forma de gota,\n recheado com frango e empanado.",},
        {"word": 'Pé de Galinha', "desc": "Prato polêmico feito com os pés da galinha,\n muito consumido em caldos ou cozidos.",},
        {"word": 'Sardinha', "desc": "Peixe pequeno e saboroso,\n pode ser servido grelhado,\n em lata ou em preparos caseiros.",},
        {"word": 'Quiabo', "desc": "Vegetal verde, \npolêmico por sua textura viscosa, \ncomum em pratos como frango com quiabo.",},
        {"word": 'Pamonha Doce', "desc": "Quitute típico de milho cozido, \nenvolto em palha, com sabor adocicado.",},
        {"word": 'Brocolis', "desc": "Vegetal verde rico em fibras e nutrientes,\n geralmente cozido ou refogado.",},
    ],
    
    "Objeto": [
        {"word": 'Grampeador', "desc": "Objeto de escritório\n usado para prender folhas de papel\n com grampos de metal.",},
        {"word": 'Relogio de pendulo', "desc": "Relógio antigo\n que funciona com um pêndulo oscilante,\n geralmente decorativo.",},
        {"word": 'Canivete', "desc": "Ferramenta dobrável com lâminas e acessórios,\n útil em situações práticas e de sobrevivência.",},
        {"word": 'Lanterna', "desc": "Dispositivo portátil\n usado para iluminar ambientes escuros\n com luz artificial.",},
        {"word": 'Garrafa térmica', "desc": "Recipiente que conserva líquidos\n quentes ou frios por mais tempo.",},
        {"word": 'Lampião', "desc": "Fonte de luz antiga alimentada por querosene,\n comum antes da eletricidade.",},
        {"word": 'Maçaneta', "desc": "Peça usada para abrir ou fechar portas,\n geralmente giratória.",},
        {"word": 'Travesseiro', "desc": "Almofada macia usada para apoiar\n a cabeça durante o sono.",},
        {"word": 'Cutelo', "desc": "Faca grande e pesada\n usada principalmente para cortar carne com osso.",},
        {"word": 'Tapete', "desc": "Peça de tecido ou material sintético\n colocada no chão para conforto ou decoração.",},
        {"word": 'Cortador de Grama', "desc": "Equipamento usado para aparar\n a grama em jardins e quintais.",},
        {"word": 'Abridor de Coco', "desc": "Ferramenta projetada para perfurar\n ou abrir cocos com segurança.",},
        {"word": 'Chaleira Elétrica', "desc": "Aparelho que aquece água rapidamente\n por meio de resistência elétrica.",},
        {"word": 'Memory Card de PS2', "desc": "Cartão de memória\n usado para salvar o progresso\n dos jogos no PlayStation 2.",},
    ],
    
    "Monstro":[
        {"word": 'Minotauro', "desc": "Criatura da mitologia grega\n com corpo de homem e cabeça de touro.",},
        {"word": 'Bicho-Papão', "desc": "Monstro folclórico usado para\n assustar crianças desobedientes,\n vive debaixo da cama ou no armário.",},
        {"word": 'Chupa-Cabra', "desc": "Criatura lendária que ataca\n animais e suga seu sangue.",},
        {"word": 'Zumbi', "desc": "Cadáver reanimado, geralmente lento\n e faminto por cérebros ou carne humana.",},
        {"word": 'Medusa', "desc": "Monstro da mitologia grega\n com cobras no lugar dos cabelos;\n quem a encara vira pedra.",},
        {"word": 'Vampiro', "desc": "Ser noturno que se alimenta\n de sangue humano, teme o sol,\n estacas e alho.",},
        {"word": 'Dragão', "desc": "Criatura mitológica gigante,\n geralmente com asas e que cospe fogo.",},
        {"word": 'Lobisomen', "desc": "Humano que se transforma em lobo\n nas noites de lua cheia,\n presente em várias culturas.",},
        {"word": 'Freddie Krugger', "desc": "Vilão dos sonhos\n que usa uma luva com lâminas\n para atacar suas vítimas enquanto dormem.",},
        {"word": 'Godzilla', "desc": "Monstro gigante japonês,\n surgido por radiação,\n famoso por destruir cidades.",},
        {"word": 'Curupira', "desc": "Ser do folclore brasileiro\n com cabelos vermelhos e pés virados para trás,\n protetor das florestas.",},
        {"word": 'Saci', "desc": "Personagem travesso do folclore brasileiro,\n de uma perna só, gorro vermelho\n e sempre em redemoinhos.",},
        {"word": 'Homem do Saco', "desc": "Figura folclórica\n usada para amedrontar crianças;\n diz-se que carrega os desobedientes num saco.",},
        {"word": 'Múmia', "desc": "Cadáver embalsamado do Egito antigo,\n que ganha vida em histórias de terror.",},
    ]
    }