# uma lista de palavras para testar o jogo
game_questions = {
    "Animal": [
        "Se você vir um desses na rua, o que você faria?",
        "Que tipo de chapéu / capacete esse animal usaria??",
        "Se você tivesse esse animal como bicho de estimação, onde você o colocaria?",
        "Esse é um animal terrestre, aquátivo ou aéreo?",
        "Na sua opnião, qual seria a profissão desse animal?",
        "Você consegue correr mais que esse animal?",
        "Você prefere enfrentar 10 galinhas do tamanho desse animal ou 10 desse animal do tamanho de uma galinha",
        "Se esse animal falasse, qual seria o sotaque ou o jeito que ele falaria?",
        "Você comeria esse animal se fosse feito pela sua vó?",
        "Se esse animal fosse um objeto, o que seria?",
        "Em um filme/desenho qual seria o super poder desse animal?",
        "Você acha que esse animal teria um cheiro bom, neutro ou ruim?",
        "Com qua frequencia você vê esse animal?",
        "Se esse animal atacasse, você morreria de forma violenta ou lentamente?"
        ],
    
    "Comida": [
        "Esse prato combina mais com um almoço de domingo ou com um lanche rápido?",
        "Em uma competição, quantas porções dessa comida você aguentaria antes de desistir / vomitar?",
        "Se, no seu aniversário, você ganhasse só essa comida, qual seria sua reação?",
        "Quantas semanas você sobreviveria comendo apenas essa comida?",
        "Essa comida daria um bom sabor de chiclete?",
        "Você comeria isso com ketchup e maionese?",
        "Como você diria que é a consistência dessa comida?",
        "Você prefere comer essa comida ou um pastel sem recheio?",
        "Você comeria essa comida como um lanche da meia noite?",
        "Entre café, refrigerante e vinho, qual bebida combina mais com essa comida?",
        "Essa comida poderia ser servida em um restaurante de luxo?",
        "Se essa comida fosse um sentimento, qual seria?",
        "Numa escala de 1 a 10, o quão bonita essa comida é?",
        "Essa comida é melhor quente, gelada ou em temperatura ambiente?",
        "Para comer essa comida, você usaria um garfo, hashis ou as mãos?",
        ],
    
    "Objeto": [
        "Onde você guardaria esse objeto?",
        "Esse objeto cumpre sua função sozinho?",
        "Você consegue encontrar isso em um escritório?",
        "Esse objeto pode ser considerado perigoso normalmente?",
        "Você daria isso como presente de aniversário para sua vó?",
        "Esse objeto seria uma arma útil em um apocalipse zumbi?",
        "Você acorda e vê esse objeto embaixo do seu travesseiro, isso é preocupante, meio estranho ou normal?",
        "Se esse objeto fosse um animal, qual seria?",
        "Você achou esse objeto no seu banheiro, qual é sua reação?",
        "Na sua profissão, é normal ver / usar esse objeto?",
        "Esse objeto seria útil no filme náufrago?",
        "Você diria que esse objeto já passou ou presenciou momentos traumáticos na vida?",
        "Você deu esse objeto para uma criança em um parquinho, o que acontece?",
        "Quais as chances desse objeto te processar por algo que você fez nele ou com ele?",
        ],
    
    "Monstro":[
        "Qual característica desse monstro você considera mais assustadora?",
        "Qual seria o super poder desse monstro?",
        "Qual seria a fraqueza desse monstro?",
        "Se esse monstro existisse, ele seria mais do ambiente urbano ou rural?",
        "O que faria para sobreviver se tivesse que enfrentar esse monstro?",
        "Como esse monstro se esconderia / disfarçaria para emboscar alguém?",
        "Esse monstro poderia aparecer durante o dia?",
        "Esse monstro é conhecido por ser forte, rapido ou sorrateiro?",
        "Qual seria o melhor esconderijo contra esse monstro?",
        "Esse monstro combina mais com risadas ou grunidos?",
        "Se esse monstro quisesse trabalhar em um emprego normal, qual seria sua profissão?",
        "Esse monstro caça sozinho ou em grupo?",
        "Esse monstro mata quem ele ver na frente ou te alvos específicos?",
    ],
    
    "Profissão":[
        "Se essa profissão fosse um vilão de filme, qual seria seu plano maligno?",
        "Se essa profissão fosse um animal, qual seria?",
        "Qual seria a arma secreta dessa profissão em uma batalha?",
        "As habilidades dessa profissão são úteis em um apocalipse zumbi? Como?",
        "Essa profissão é mais comum na cidade ou no campo?",
        "Essa profissão é perigosa?",
        "Precisa de muitos anos de estudo para exercer essa profissão?",
        "Você trabalharia nessa profissão",
        "É uma profissão que exige mais força física ou mental?",
        "Qual seria o superpoder inútil que todo profissional dessa área teria?",
        "Qual seria o pior conselho que alguém dessa profissão poderia dar?",
        "Qual a pior coisa que alguém nessa profissão pode fazer?",
        "O que alguém nessa profissão faz no tempo livre?",
    ],
    
    "Lugar":[
        "Você já visitou esse lugar alguma vez na vida?",
        "O quão divertido seria você ir nesse lugar durante as suas férias?",
        "Esse lugar costuma ser barulhento ou silencioso?",
        "É um lugar aberto ou fechado?",
        "Esse lugar é acessível para pessoas com mobilidade reduzida?",
        "É um lugar frequentado por muitas pessoas ao mesmo tempo?",
        "Como você se sentiria indo a esse lugar sozinho?",
        "Sua vó foi nesse local e trouxe uma coisa de lá pra você provar, voce prova?",
        "Você ve um casal tirando várias fotos e rindo bastante nesse local, qual sua reação?",
        "Qual personagem (de filme, desenho, etc) você imagina que viveria aqui?",
        "Que tipo de frase ou pergunta que combina com esse local?",
        "Você vê uma pessoa de jaleco nesse local, o que você pensa disso?",
        "Que diferença faria pra você se esse lugar não existisse mais?",
        
    ],
    
    "Veículos":[
        "Ele é movido por força humana, motor ou outro tipo de energia?",
        "Você se sentiria seguro viajando nesse transporte? Por quê?",
        "Esse transporte pode levar mais de 5 pessoas ao mesmo tempo?",
        "Você comumente vê esse meio de transporte",
        "Você precisaria de uma habilitação especial para usá-lo?",
        "Esse meio de transporte é rápido ou lento?",
        "Você acha que esse transporte seria útil numa ilha deserta?",
        "Esse transporte é mais usado para lazer ou trabalho?",
        "Você precisaria de proteção (capacete, cinto, colete) para usá-lo?",
        "Você acha que esse transporte pode ser perigoso para crianças?",
        "Faria diferença direta na sua vida não poder usar mais esse transporte?",
        "Se esse transporte fosse um animal, qual seria?",
        "Qual você acha que seria a personalidade desse transporte?",
        "Você acha que o Batman teria um veículo desse como um 'Bat-Transporte'?",  
    ]
    }

